name: Deploy to Koyeb
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u matsukenbass --password-stdin
      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/matsukenbass/my-project:latest
          file: ./Dockerfile
          build-args: |
            "PAYLOAD_SECRET=${{vars.PAYLOAD_SECRET}}"
            "MONGODB_URL=${{vars.MONGODB_URL}}"
            "NEXT_PUBLIC_SERVER_URL=${{vars.NEXT_PUBLIC_SERVER_URL}}"
            "RESEND_API_KEY=${{vars.RESEND_API_KEY}}"
            "STRIPE_SECRET_KEY=${{vars.STRIPE_SECRET_KEY}}"
            "STRIPE_WEBHOOK_SECRET=${{vars.STRIPE_WEBHOOK_SECRET}}"
            "AWS_REGION=${{vars.AWS_REGION}}"
            "S3_ACCESS_KEY_ID=${{vars.S3_ACCESS_KEY_ID}}"
            "S3_SECRET_ACCESS_KEY=${{vars.S3_SECRET_ACCESS_KEY}}"
            "NEXT_PUBLIC_AWS_ACCESS_KEY=${{vars.NEXT_PUBLIC_AWS_ACCESS_KEY}}"
            "NEXT_PUBLIC_AWS_SECRET=${{vars.NEXT_PUBLIC_AWS_SECRET}}"
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: '${{ secrets.KOYEB_TOKEN }}'
          github_token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Deploy to Koyeb
        run: koyeb service redeploy digital-ec/digital-ec
